CREATE TYPE nanp;

CREATE OR REPLACE FUNCTION nanp_in( CSTRING )
    RETURNS nanp
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION nanp_out( nanp )
    RETURNS CSTRING
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE TYPE nanp (
    INPUT = nanp_in,
    OUTPUT = nanp_out,
    INTERNALLENGTH = 8,
    PASSEDBYVALUE = TRUE,
    ALIGNMENT = double,
    STORAGE = plain
);
